
version: 2.1
orbs:
  architect: giantswarm/architect@4.23.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-docker:
          name: "push-to-docker"
          image: "quay.io/giantswarm/opensearch-certs"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          name: "push-to-aliyun-master"
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/opensearch-certs"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/
